name: "Run nix build"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - run: nix build -I nixpkgs=channel=nixos-${{ matrix.env }} '(import <nixpkgs> {}).haskellPackages.callPackage ./. {}'
    strategy:
      matrix:
        env: [19.09, unstable]
