name: "Run nix build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - run: nix build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-${{ matrix.env }} '(import <nixpkgs> {}).haskellPackages.callPackage ./. {}'
    strategy:
      matrix:
        env: [19.09, unstable]
